language: ruby
cache: bundler
bundler_args: --without benchmarks console tools
script: "bundle exec rake ci"
after_success:
  - '[ -d coverage ] && codeclimate-test-reporter'
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - jruby-9.1.13.0
env:
  global:
    - COVERAGE="true"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
